// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

export interface Folder { folder_name: string, notes: Array<Note>, }