// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Note { folder_name: string, name: string, ext: string, intermediate_ext: string, content: string | null, }